AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An example AWS SAM template that creates a Lambda application.

Globals:
  Function:
    Timeout: 10

Parameters:
  SquareApiKey:
    Type: String
    Description: Square API Key
  ServiceVariationVersion:
    Type: String
    Description: Service Variation Version
  ServiceVariationId:
    Type: String
    Description: Service Variation ID
  TeamMemberId:
    Type: String
    Description: Team Member ID
  CustomerId:
    Type: String
    Description: Customer ID
  LocationId:
    Type: String
    Description: Location ID
  VertexJson:
    Type: String
    Description: Vertex JSON

Resources:
  GoHello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/golang/hello
      Handler: index.handler
      Runtime: go1.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /golang/hello
            Method: get

  CreateSquareBooking:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/golang/squareApi/createBooking
      Handler: index.handler
      Runtime: go1.x
      Environment:
        Variables:
          SQUARE_API_KEY:
            Fn::Ref: SquareApiKey
          SERVICE_VARIATION_VERSION:
            Fn::Ref: ServiceVariationVersion
          SERVICE_VARIATION_ID:
            Fn::Ref: ServiceVariationId
          TEAM_MEMBER_ID:
            Fn::Ref: TeamMemberId
          CUSTOMER_ID:
            Fn::Ref: CustomerId
          LOCATION_ID:
            Fn::Ref: LocationId
      Events:
        CreateSquareBooking:
          Type: Api
          Properties:
            Path: /create/booking
            Method: post

  NodeHello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/node/hello
      Handler: index.main
      Runtime: nodejs18.x
      Events:
        NodeAndy:
          Type: Api
          Properties:
            Path: /node/hello
            Method: get

  GVertextAI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/python/googleAI/vertex
      Handler: index.handler
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          VERTEX_JSON:
            Fn::Ref: VertexJson
      Events:
        PythonRoute:
          Type: Api
          Properties:
            Path: /ai/vertex
            Method: get
